CAPTURE_ERROR_CODE_MEANINGS = {
    '2': 'ORDER_REF missing or incorrect',
    '3': 'ORDER_AMOUNT missing or incorrect',
    '4': 'ORDER_CURRENCY is missing or incorrect',
    '5': 'IDN_DATE is not in the correct format',
    '6': 'Error confirming order',
    '7': 'Order already confirmed',
    '9': 'Invalid ORDER_REF',
    '10': 'Invalid ORDER_AMOUNT',
    '11': 'Invalid ORDER_CURRENCY',
    '12': 'Invalid CHARGE_AMOUNT',
    '13': 'Invalid signature',
    '14': 'Limit calls for API exceeded',
    '15': 'Limit calls for API exceeded for this merchant',
    '18': 'Invalid request',
    '20': 'Partial amount is not supported or enabled',
}

REFUND_ERROR_CODE_MEANINGS = {
    '2': 'ORDER_REF missing or incorrect',
    '3': 'ORDER_AMOUNT missing or incorrect',
    '4': 'ORDER_CURRENCY is missing or incorrect',
    '5': 'IRN_DATE is not in the correct format',
    '6': 'Error cancelling order',
    '7': 'Order already cancelled',
    '8': 'Unknown error',
    '9': 'Invalid ORDER_REF',
    '10': 'Invalid ORDER_AMOUNT',
    '11': 'Invalid ORDER_CURRENCY',
    '12': 'PRODUCTS_IDS missing or format incorrect',
    '13': 'PRODUCTS_QTY missing or format incorrect',
    '14': 'Invalid PRODUCTS_QTY',
    '15': 'Invalid REGENERATE_CODES',
    '16': 'Invalid LICENSE_HANDLING',
    '17': 'AMOUNT missing or format incorrect',
    '18': 'Invalid AMOUNT',
    '19': 'Invalid MERCHANT',
    '20': 'IRN Disabled',
    '21': 'Extra parameter ORDER_MPLACE_MERCHANT or ORDER_MPLACE_AMOUNT sent',
    '22': 'ORDER_MPLACE_MERCHANT missing or format incorrect',
    '23': 'ORDER_MPLACE_AMOUNT missing or format incorrect',
    '24': 'Invalid ORDER_MPLACE_MERCHANT[] (invalid marketplace seller code)',
    '25': 'Invalid ORDER_MPLACE_AMOUNT[] (invalid marketplace seller amount)',
    '26': 'ORDER_MPLACE_MERCHANT[] and ORDER_MPLACE_AMOUNT[] not synchronized',
    '27': 'Amount mismatch',
    '28': 'ORDER_MPLACE_MERCHANT[] contains a duplicate value',
    '29': 'Refund allowed time interval has expired for this Order',
    '30': 'This payment method does not support refunds',
    '31': 'Number of maximum refunds for this order reached',
    '32': 'Multiple refund is not allowed for this order or the amount for refunds exceeded the total '
          'amount of the order',
    '33': 'ORDER_MPLACE_MERCHANT or ORDER_MPLACE_AMOUNT can not be used with PRODUCT_IDS parameter. '
          'Refund by product is not allowed for Marketplace order',
    '34': 'LOYALTY_POINTS_AMOUNT programs are invalid',
    '35': 'Available loyalty points are insufficient to cover requested loyalty points amount for '
          'this order',
    '36': 'Limit calls for IRN exceeded',
    '37': 'Limit calls for IRN exceeded for this merchant',
    '38': 'The partial IRN is not supported without products node',
    '39': 'The terminal for this order is invalid.',
    '40': 'Invalid product amount',
    '41': 'Invalid request body',
    '42': 'Product SKU does not exist',
    '43': 'Product amount, included past refunds, exceeds original amount',
    '44': 'Partial IRN is not allowed if order status is AUTHRECEIVED',
    '45': 'Marketplace validation against number of products failed',
    '47': 'Invalid commission currency for marketplace product',
    '48': 'Commission amount exceeds original commission amount',
    '49': 'Amount exceeds original amount',
    '50': 'Invalid seller for marketplace product',
    '51': 'Refund is not allowed because order status is invalid',
    '52': 'Invalid marketplace products structure',
    '46': 'Invalid marketplace order id',
    '53': 'Invalid installments return amount',
    '54': 'Installments product must be specified on root level for this type of request.',
    '55': 'Invalid value for Fast Refund parameter',
    '56': 'Fast Refund feature is not available',
}
