# Generated by Django 2.1 on 2018-10-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_update_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
