# Generated by Django 2.2.4 on 2019-09-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_operation'),
        ('billing', '0013_service_external_billing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='recurring_payments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecurringPaymentsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(db_index=True, max_length=255)),
                ('order', models.IntegerField(default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
            options={
                'unique_together': {('gateway_name', 'client')},
            },
        ),
    ]
