# Generated by Django 2.2.4 on 2019-09-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_add_recurrent_payments_enabled_field_and_model_for_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='external_billing_id',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
    ]
