# Generated by Django 2.2.4 on 2019-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_remove_unique_from_service_ext_billing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fiscal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_fiscal',
            field=models.BooleanField(default=False),
        ),
    ]
