# Generated by Django 2.2.5 on 2019-09-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0018_update_country_field_on_invoice_and_taxrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reseller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
