# Generated by Django 2.0.2 on 2018-02-20 09:50

from django.db import migrations, transaction, utils


def add_resources_with_details(apps, schema_editor):
    """Add osbilling resources with attributes and metrics"""
    resource = apps.get_model("osbilling", "BillingResource")
    instance = {'display_name': 'Instance',
                'type': 'service',
                'name': 'instance',
                'definition': {"attributes": [{"type": "string",
                                               "name": "availability_zone"},
                                              {"type": "string",
                                               "name": "instance_type"},
                                              {"type": "string",
                                               "name": "display_name"},
                                              {"type": "string",
                                               "name": "cell_name"},
                                              {"type": "datetime",
                                               "name": "launched_at"},
                                              {"type": "string",
                                               "name": "state"},
                                              {"type": "integer",
                                               "name": "vcpus"},
                                              {"type": "integer",
                                               "name": "root_gb",
                                               "value_size": 'g'},
                                              {"type": "string",
                                               "name": "os_type"},
                                              {"type": "string",
                                               "name": "os_version"}]}}
    image = {'display_name': 'Image',
             'type': 'service',
             'name': 'image',
             'definition': {"attributes": [{"value_size": "b",
                                            "type": "integer",
                                            "name": "size"},
                                           {"type": "string",
                                            "name": "status"},
                                           {"type": "string",
                                            "name": "name"}]}}

    volume = {'display_name': 'Volume',
              'type': 'service',
              'name': 'volume',
              'definition': {"attributes": [{"value_size": "g",
                                             "type": "integer",
                                             "name": "size"},
                                            {"type": "string",
                                             "name": "volume_type"},
                                            {"type": "string",
                                             "name": "display_name"}]}}

    bandwidth = {'display_name': 'Network',
                 'type': 'metric',
                 'name': 'network',
                 'definition': {"metrics": [{"rescale_to": "g",
                                             "name": "bandwidth",
                                             "aggregation": "sum",
                                             "reaggregation": "sum",
                                             "granularity": 3600,
                                             "unit": "b"}]}}

    try:
        with transaction.atomic():
            resource.objects.create(**instance)
    except utils.IntegrityError:
        pass
    try:
        with transaction.atomic():
            resource.objects.create(**image)
    except utils.IntegrityError:
        pass
    try:
        with transaction.atomic():
            resource.objects.create(**volume)
    except utils.IntegrityError:
        pass
    try:
        with transaction.atomic():
            resource.objects.create(**bandwidth)
    except utils.IntegrityError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('osbilling', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_resources_with_details),
    ]
