# Generated by Django 2.1.5 on 2019-02-05 12:31

from django.db import migrations, transaction, utils


def add_resources_with_details(apps, schema_editor):
    """Add osbilling resources with attributes and metrics"""
    resource = apps.get_model("osbilling", "BillingResource")
    instance_definition = {"attributes": [{"type": "string",
                                           "name": "availability_zone"},
                                          {"type": "string",
                                           "name": "instance_type"},
                                          {"type": "string",
                                           "name": "display_name"},
                                          {"type": "string",
                                           "name": "cell_name"},
                                          {"type": "datetime",
                                           "name": "launched_at"},
                                          {"type": "string",
                                           "name": "state"},
                                          {"type": "integer",
                                           "name": "vcpus"},
                                          {"type": "integer",
                                           "name": "root_gb",
                                           "value_size": 'g'},
                                          {"value_size": "m",
                                           "name": "memory_mb",
                                           "type": "integer"},
                                          {"type": "string",
                                           "name": "os_type"},
                                          {"type": "string",
                                           "name": "os_version"},
                                          {"type": "string",
                                           "name": "instance_id"},
                                          {"type": "string",
                                           "name": "tenant_id"},
                                          {"type": "string",
                                           "name": "host"},
                                          {"type": "integer",
                                           "name": "ephemeral_gb",
                                           "value_size": "g"}]}
    image_definition = {"attributes": [{"value_size": "b",
                                        "type": "integer",
                                        "name": "size"},
                                       {"type": "datetime",
                                        "name": "created_at"},
                                       {"type": "datetime",
                                        "name": "updated_at"},
                                       {"type": "string",
                                        "name": "disk_format"},
                                       {"type": "string",
                                        "name": "visibility"},
                                       {"type": "string",
                                        "name": "status"},
                                       {"type": "string",
                                        "name": "name"}]}

    volume_definition = {"attributes": [{"value_size": "g",
                                         "type": "integer",
                                         "name": "size"},
                                        {"type": "string",
                                         "name": "availability_zone"},
                                        {"type": "datetime",
                                         "name": "created_at"},
                                        {"type": "string",
                                         "name": "volume_type"},
                                        {"type": "string",
                                         "name": "display_name"}]}

    bandwidth_definition = {"metrics": [{"rescale_to": "g",
                                         "name": "bandwidth",
                                         "aggregation": "sum",
                                         "reaggregation": "sum",
                                         "granularity": 3600,
                                         "unit": "b"}]}

    try:
        with transaction.atomic():
            resource.objects.filter(name='instance').update(definition=instance_definition)
            resource.objects.filter(name='image').update(definition=image_definition)
            resource.objects.filter(name='volume').update(definition=volume_definition)
            resource.objects.filter(name='bandwidth').update(definition=bandwidth_definition)
    except utils.IntegrityError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('osbilling', '0003_update_pricing_rules'),
    ]

    operations = [
        migrations.RunPython(add_resources_with_details),
    ]
