# Generated by Django 2.1.7 on 2019-02-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbilling', '0008_update_billing_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceusagelog',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
