# Generated by Django 2.1.7 on 2019-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbilling', '0010_billing_reporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopenstackmonthlyreporting',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientopenstackmonthlyreporting',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientopenstackmonthlyreporting',
            name='uptodate_credit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, null=True),
        ),
    ]
