# Generated by Django 2.1.7 on 2019-04-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbilling', '0011_client_os_monthly_reporting_adjustments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Currency'),
        ),
    ]
