# Generated by Django 2.1.5 on 2019-02-05 12:31

from django.db import migrations
from django.db import transaction
from django.db import utils


def add_traffic_resource(apps, schema_editor):
    """Add osbilling resources with attributes and metrics"""
    del schema_editor  # unused
    resource = apps.get_model("osbilling", "BillingResource")

    traffic_resource_definition = {
        "metrics": [
            {
                "name": "incoming_public_traffic",
            },
            {
                "name": "incoming_private_traffic",
            },
            {
                "name": "outgoing_public_traffic",
            },
            {
                "name": "outgoing_private_traffic",
            },
            {
                "name": "total_private_traffic",
            },
            {
                "name": "total_public_traffic",
            },
            {
                "name": "total_traffic",
            },
        ],
        "attributes": [
            {
                "type": "string",
                "name": "availability_zone"
            },
            {
                "type": "string",
                "name": "instance_type"
            },
            {
                "type": "string",
                "name": "display_name"
            },
            {
                "type": "string",
                "name": "cell_name"
            },
            {
                "type": "datetime",
                "name": "launched_at"
            },
            {
                "type": "string",
                "name": "state"
            },
            {
                "type": "integer",
                "name": "vcpus"
            },
            {
                "type": "integer",
                "name": "root_gb",
                "value_size": 'g'
            },
            {
                "type": "string",
                "name": "os_type"
            },
            {
                "type": "string",
                "name": "os_version"
            }
        ]
    }

    try:
        with transaction.atomic():
            resource.objects.create(name='instance_traffic',
                                    type='internal',
                                    display_name='Instance traffic',
                                    definition=traffic_resource_definition)
    except utils.IntegrityError:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('osbilling', '0012_make_currency_on_delete_protected_for_pricingplan'),
    ]

    operations = [
        migrations.RunPython(add_traffic_resource),
    ]
