# Generated by Django 2.1.5 on 2019-02-05 12:31

from django.db import migrations
from django.db import transaction
from django.db import utils


def add_traffic_resource(apps, schema_editor):
    """Add osbilling resources with attributes and metrics"""
    del schema_editor  # unused
    resource = apps.get_model("osbilling", "BillingResource")

    ceph_metrics = {
        "metrics": [
            {
                "name": "radosgw.api.requests",
                "aggregation": "sum",
                "reaggregation": "sum",
                "granularity": 300
            },
            {
                "name": "radosgw.objects",
                "aggregation": "mean",
                "reaggregation": "mean",
                "granularity": 300
            },
            {
                "name": "radosgw.objects.containers",
                "aggregation": "mean",
                "reaggregation": "mean",
                "granularity": 300
            },
            {
                "rescale_to": "g",
                "name": "radosgw.objects.size",
                "aggregation": "mean",
                "reaggregation": "mean",
                "granularity": 300,
                "unit": "b"
            }
        ]
    }

    try:
        with transaction.atomic():
            resource.objects.create(name='ceph_account',
                                    type='metric',
                                    display_name='Ceph object storage',
                                    definition=ceph_metrics)
    except utils.IntegrityError:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('osbilling', '0013_add_traffic_resource'),
    ]

    operations = [
        migrations.RunPython(add_traffic_resource),
    ]
