# Generated by Django 2.1.5 on 2019-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbilling', '0005_modifier_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrulecondition',
            name='operator',
            field=models.CharField(choices=[('lt', 'Less than'), ('le', 'Less or equal'), ('gt', 'Greater than'), ('ge', 'Greater or equal'), ('eq', 'Equal'), ('ne', 'Not equal'), ('in', 'In list'), ('ni', 'Not in list')], default='eq', max_length=2),
        ),
        migrations.AlterField(
            model_name='pricingrulemodifier',
            name='operator',
            field=models.CharField(choices=[('lt', 'Less than'), ('le', 'Less or equal'), ('gt', 'Greater than'), ('ge', 'Greater or equal'), ('eq', 'Equal'), ('ne', 'Not equal'), ('in', 'In list'), ('ni', 'Not in list')], default='eq', max_length=2),
        ),
    ]
