# Generated by Django 2.1.7 on 2019-03-01 09:42

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_extra_statuses'),
        ('osbilling', '0009_osbilling_resources_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOpenStackMonthlyReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('uptodate_credit', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('usage', jsonfield.fields.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_os_monthly_reporting', to='core.Client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_os_monthly_reporting', to='osbilling.PricingPlan')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
