# Generated by Django 2.0.2 on 2018-02-20 09:50

from django.db import migrations, transaction, utils


def add_services_to_client_billing(apps, schema_editor):
    client_billing_model = apps.get_model('osbilling', 'ClientBilling')
    service_model = apps.get_model('billing', 'Service')
    for client_billing in client_billing_model.objects.all():
        os_services_qs = service_model.objects.filter(
            client=client_billing.client, product__product_type='openstack'
        )
        active_os_service = os_services_qs.filter(openstack_project__isnull=False).first()
        if active_os_service:
            client_billing.service = active_os_service
            client_billing.save()
        else:
            inactive_os_service = os_services_qs.first()
            if inactive_os_service:
                client_billing.service = inactive_os_service
                client_billing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osbilling', '0016_clientbilling_service'),
    ]

    operations = [
        migrations.RunPython(add_services_to_client_billing),
    ]
