# Generated by Django 2.2.5 on 2019-10-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_product_hide_services'),
        ('osbilling', '0018_change_client_billing_to_service_dynamic_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedynamicusage',
            name='reseller_service',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_service_dynamic_usage', to='billing.Service'),
        ),
        migrations.AlterField(
            model_name='servicedynamicusage',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_dynamic_usage', to='billing.Service'),
        ),
    ]
