# Generated by Django 2.1 on 2018-09-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpanelSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpanel_package_id', models.IntegerField()),
                ('cpanel_group_id', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpanel_plugin_settings', to='billing.Product')),
            ],
        ),
    ]
