# Generated by Django 2.1.4 on 2018-12-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_move_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingserversettings',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_server_settings', to='servers.Server'),
        ),
    ]
