# Generated by Django 2.2.5 on 2019-11-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
        ('conf', '0003_allow_blank_reseller_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='reseller',
        ),
        migrations.AddField(
            model_name='configuration',
            name='reseller_resources',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='reseller.ResellerResources'),
        ),
    ]
