# Generated by Django 2.2.5 on 2019-11-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_resellerresources_service'),
        ('conf', '0004_change_reseller_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='configuration',
            unique_together={('name', 'reseller_resources')},
        ),
    ]
