# Generated by Django 2.1.2 on 2018-12-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0004_move_auto_create_openstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='flavor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='openstack.OpenstackInstanceFlavor'),
        ),
    ]
