# Generated by Django 2.1.5 on 2019-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0007_image_hypervisor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='flavor_groups',
            field=models.ManyToManyField(blank=True, related_name='images', to='openstack.FlavorGroup'),
        ),
        migrations.AddField(
            model_name='image',
            name='flavors',
            field=models.ManyToManyField(blank=True, related_name='images', to='openstack.OpenstackInstanceFlavor'),
        ),
    ]
