# Generated by Django 2.1.7 on 2019-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0010_add_hypervisors_and_host_name_field_for_instances'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenstackRole',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Openstack roles',
            },
        ),
    ]
