# Generated by Django 2.1.7 on 2019-03-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0012_change_image_to_foreign_key_on_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
