# Generated by Django 2.1.7 on 2019-04-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_client_credit_left'),
        ('openstack', '0014_image_os_distro_field_without_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenstackProductSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_get_me_a_network_on_auto_setup', models.BooleanField(default=False)),
                ('network_auto_allocated_topology_regions', models.ManyToManyField(blank=True, related_name='os_product_settings', to='openstack.OpenstackRegion')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openstack_product_settings', to='billing.Product')),
            ],
        ),
    ]
