# Generated by Django 2.2 on 2019-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0017_networktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackinstanceflavor',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
