# Generated by Django 2.2.2 on 2019-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0021_hypervisor_hypervisor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackregion',
            name='disable_for_enduser',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
