# Generated by Django 2.2.5 on 2019-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0026_image_volume_snapshot_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='stopped_by_fleio',
            field=models.BooleanField(default=False),
        ),
    ]
