# Generated by Django 2.2.5 on 2019-10-30 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openstack', '0028_flavorgroup_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackinstanceflavor',
            name='reseller',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
