# Generated by Django 2.2.5 on 2019-11-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0029_openstackinstanceflavor_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackinstanceflavor',
            name='properties',
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
    ]
