# Generated by Django 2.2.5 on 2019-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_resellerresources_service'),
        ('openstack', '0031_change_reseller_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackinstanceflavor',
            name='used_by_resellers',
            field=models.ManyToManyField(related_name='visible_staff_flavors', to='reseller.ResellerResources'),
        ),
    ]
