# Generated by Django 2.0.2 on 2018-02-19 16:02

from django.db import migrations


def create_default_configuration(apps, schema_migration):
    """Create the default Configurations"""
    conf = apps.get_model('conf', 'Configuration')
    conf.objects.create(name='default', is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_default_currency'),
    ]

    operations = [
        migrations.RunPython(create_default_configuration),
    ]
