# Generated by Django 2.1.2 on 2018-12-07 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=10240, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_type', models.CharField(max_length=48, unique=True)),
            ],
            options={
                'verbose_name_plural': 'App statuses',
            },
        ),
    ]
