# Generated by Django 2.1.4 on 2019-01-11 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgroup',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
