# Generated by Django 2.2.1 on 2019-06-03 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_extra_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondFactorAuthType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Second factor authentication type name', max_length=64)),
                ('enabled_to_staff', models.BooleanField(default=False)),
                ('enabled_to_enduser', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondFactorAuthMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SecondFactorAuthType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type')},
            },
        ),
    ]
