# Generated by Django 2.2.5 on 2019-10-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fleio.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client_user_reseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigIntegerField(default=fleio.core.utils.RandomId('core.TermsOfService'), primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=10240)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=32)),
                ('draft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfServiceAgreement',
            fields=[
                ('id', models.BigIntegerField(default=fleio.core.utils.RandomId('core.TermsOfServiceAgreement'), primary_key=True, serialize=False, unique=True)),
                ('agreed', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('terms_of_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TermsOfService')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('terms_of_service', 'user')},
            },
        ),
    ]
