# Generated by Django 2.2.5 on 2019-10-30 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reseller_blank_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='permissions',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PermissionSet'),
        ),
        migrations.AlterField(
            model_name='usertoclient',
            name='permissions',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
