# Generated by Django 2.0.2 on 2018-02-19 15:35

from django.db import migrations


def load_default_currency(apps, schema_editor):
    currency = apps.get_model('core', 'Currency')
    if not currency.objects.exists():
        eur = currency(code='EUR', is_default=True)
        eur.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_default_currency),
    ]
