# Generated by Django 2.1.2 on 2018-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_default_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_point', models.CharField(db_index=True, max_length=128)),
                ('code', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('frontend_file_type', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customcode',
            unique_together={('insertion_point', 'frontend_file_type')},
        ),
    ]
