# Generated by Django 2.1.5 on 2019-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_is_default_to_user_and_client_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_billing_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
