# Generated by Django 2.1.7 on 2019-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_has_billing_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('deleting', 'Deleting')], db_index=True, default='active', max_length=16),
        ),
    ]
