# Generated by Django 2.2.1 on 2019-06-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_secondfactorauthmethod_secondfactorauthtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
