# Generated by Django 2.0.2 on 2018-02-19 15:32

import pycountry

from django.db import migrations


def update_countries(apps, schema_editor):
    countries = {country.alpha_2: country.name for country in pycountry.countries}
    tax_rule = apps.get_model('billing', 'TaxRule')
    for rule in tax_rule.objects.all():
        rule.country = countries[rule.country]
        rule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(update_countries),
    ]
