# Generated by Django 2.1.2 on 2018-10-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_visible_fix_spelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.ProductCycle'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='upgrades',
            field=models.ManyToManyField(blank=True, related_name='_product_upgrades_+', to='billing.Product'),
        ),
        migrations.AddField(
            model_name='service',
            name='task',
            field=models.CharField(blank=True, choices=[('changing', 'Changing')], db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('serviceUpgrade', 'Service Upgrade'), ('credit', 'Credit Balance'), ('setupfee', 'Setup Fee'), ('other', 'Other')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('serviceUpgrade', 'Service Upgrade'), ('credit', 'Credit Balance'), ('other', 'Other')], db_index=True, max_length=16),
        ),
    ]
