# Generated by Django 2.1.7 on 2019-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_serviceassignedip_servicehostingaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='domain_action',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='domain_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_domain',
            field=models.BooleanField(default=False),
        ),
    ]
