# Generated by Django 2.2.4 on 2019-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_fix_romcard_external_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='external_billing_id',
            field=models.CharField(blank=True, max_length=38, null=True, unique=True),
        ),
    ]
