# Generated by Django 2.2.5 on 2019-10-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_product_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_services',
            field=models.BooleanField(default=False),
        ),
    ]
