# Generated by Django 2.2.5 on 2019-11-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_configurableoption_reseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurableoption',
            name='reseller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reseller',
        ),
    ]
