# Generated by Django 2.1.2 on 2018-12-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_serviceassignedip_servicehostingaccount'),
        ('cpanelserver', '0002_rename_product_settings_and_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpanelserverproductsettings',
            name='server_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.ServerGroup'),
        ),
    ]
