# Generated by Django 2.1 on 2018-09-10 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('args', jsonfield.fields.JSONField(blank=True, default=[], null=True)),
                ('kwargs', jsonfield.fields.JSONField(blank=True, default=[], null=True)),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='The Fleio resource this task is associated with.', max_length=64, null=True)),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='The Fleio resource type, like service, order, user, project', max_length=16, null=True)),
                ('state', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasklog.Task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taskrun',
            unique_together={('task', 'retry')},
        ),
    ]
