# Generated by Django 2.1.7 on 2019-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklog', '0002_allow_longer_resource_id_in_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resource_type',
            field=models.CharField(blank=True, db_index=True, help_text='The Fleio resource type, like service, order, user, project', max_length=32, null=True),
        ),
    ]
