# Generated by Django 2.1 on 2018-09-10 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DispatcherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('seen', 'Seen'), ('error', 'Error')], db_index=True, default='pending', max_length=10)),
                ('status_detail', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Dispatchers logs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('variables', jsonfield.fields.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.Client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('content', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=255)),
                ('template_engine', models.CharField(default='django', max_length=32)),
                ('dispatcher', models.CharField(db_index=True, default='all', max_length=64)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.Category')),
            ],
            options={
                'verbose_name_plural': 'Notification templates',
            },
        ),
        migrations.AddField(
            model_name='dispatcherlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatchers_log', to='notifications.Notification'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('name', 'dispatcher')},
        ),
    ]
