# Generated by Django 2.0.2 on 2018-02-20 09:11

from django.db import migrations


def add_general_category(apps, schema_editor):
    category = apps.get_model('notifications.Category')
    category.objects.create(name='general', description='General messages')


def add_credit_category(apps, schema_editor):
    category = apps.get_model('notifications.Category')
    category.objects.create(name='credit', description='Account credit')


def add_account_category(apps, schema_editor):
    category = apps.get_model('notifications.Category')
    category.objects.create(name='account', description='User account related messages')


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_general_category),
        migrations.RunPython(add_credit_category),
        migrations.RunPython(add_account_category),
    ]
