# Generated by Django 2.1.2 on 2018-10-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_language_for_notification_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.Client'),
        ),
    ]
