# Generated by Django 2.1 on 2018-09-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('billing', '0003_update_countries'),
        ('cpanelserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('ProductSettings', 'CpanelServerProductSettings'),
        migrations.AlterField(
            model_name='CpanelServerProductSettings',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='cpanelserver_product_settings', to='billing.Product'),
        ),
    ]
