# Generated by Django 2.1.2 on 2018-12-07 11:25
import logging
from django.db import migrations
from fleio.billing.models import ServiceConfigurableOption, ServiceHostingAccount

LOG = logging.getLogger(__name__)


def migrate_from_account_to_service_account(apps, schema_editor):
    """ CAN BE REMOVED ON MIGRATIONS SQUASH
    This moves the cpanelserver Account data to the billing model ServiceHostingAccount
    """
    account = apps.get_model('cpanelserver', 'Account')
    for acc in account.objects.all():
        domain = acc.domain
        scfo = ServiceConfigurableOption.objects.filter(option__name='domain_name',
                                                        option_value=domain,
                                                        service__status='active',
                                                        service__product__module__plugin__app_label='cpanelserver').first()
        if scfo and acc.server:
            server = acc.server
            if ServiceHostingAccount.objects.filter(service=scfo.service).count() == 0:
                ServiceHostingAccount.objects.create(service=scfo.service,
                                                     server_id=server.pk,
                                                     package_name=acc.plan,
                                                     account_id=domain,
                                                     username=acc.user)


class Migration(migrations.Migration):

    dependencies = [
        ('cpanelserver', '0003_account_switch'),
    ]

    operations = [
        migrations.RunPython(migrate_from_account_to_service_account)
    ]
