# Generated by Django 2.1.2 on 2018-12-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanelserver', '0004_move_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='server',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
