# Generated by Django 2.1.2 on 2018-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='notification_on_staff_user_reply_to_user',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='notification_on_user_reply_to_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='notify_cc_recipients_on_ticket_close',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='notify_cc_recipients_on_ticket_open',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='notify_cc_recipients_on_ticket_reply',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(max_length=127, unique=True),
        ),
    ]
