# Generated by Django 2.1.2 on 2018-12-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_make_tickets_internal_status_nullable_and_default_it_to_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
