# Generated by Django 2.1.5 on 2019-02-08 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_add_configurable_ticket_id_by_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_reply_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
