# Generated by Django 2.2.2 on 2019-06-24 08:00

from django.db import migrations, models
import fleio.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_last_reply_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigIntegerField(default=fleio.core.utils.RandomId('tickets.Attachment'), primary_key=True, serialize=False, unique=True),
        ),
    ]
