# Generated by Django 2.2.3 on 2019-08-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='public_key',
            field=models.TextField(max_length=17408),
        ),
    ]
