# Generated by Django 2.1.2 on 2018-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_add_epp_flag_and_domain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='registration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='registration_period',
            field=models.IntegerField(default=1),
        ),
    ]
