# Generated by Django 2.1.2 on 2018-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_registration_date_period_and_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tld',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
