# Generated by Django 2.1.2 on 2018-10-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_made_registrar_connector_class_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='epp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='ipv4',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
