# Generated by Django 2.1.4 on 2019-01-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0005_make_flavor_foreign_key_for_instances'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='openstackinstanceflavor',
            name='flavor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='openstack.FlavorGroup'),
        ),
    ]
