# Generated by Django 2.1.4 on 2019-01-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0006_add_flavor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hypervisor_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
