# Generated by Django 2.1.7 on 2019-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0009_instance_booted_from_iso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('host_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('host_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('memory_mb', models.IntegerField()),
                ('local_gb', models.IntegerField()),
                ('region', models.CharField(db_index=True, max_length=128)),
                ('sync_version', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hypervisors',
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
