# Generated by Django 2.1.7 on 2019-03-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0011_openstackrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='openstack.Image'),
        ),
    ]
