# Generated by Django 2.1.7 on 2019-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0013_instance_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='os_distro',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
