# Generated by Django 2.1.7 on 2019-04-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0016_traffic_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64, unique=True)),
                ('network', models.ManyToManyField(db_index=True, related_name='network_tags', to='openstack.Network')),
            ],
        ),
    ]
