# Generated by Django 2.2.1 on 2019-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0019_volumebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavorgroup',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
