# Generated by Django 2.2.1 on 2019-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0020_flavorgroup_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypervisor',
            name='hypervisor_type',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
