# Generated by Django 2.2.2 on 2019-07-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0023_volumebackup_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterTemplate',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('floating_ip_enabled', models.BooleanField(default=False)),
                ('master_flavor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('insecure_registry', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('no_proxy', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('https_proxy', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('http_proxy', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tls_disabled', models.BooleanField(default=False)),
                ('keypair_id', models.CharField(blank=True, max_length=255, null=True)),
                ('public', models.BooleanField(default=False)),
                ('labels', models.CharField(blank=True, max_length=1024, null=True)),
                ('docker_volume_size', models.IntegerField(default=25, null=True)),
                ('server_type', models.CharField(max_length=10)),
                ('external_network_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fixed_subnet', models.CharField(blank=True, max_length=255, null=True)),
                ('fixed_network', models.CharField(blank=True, max_length=255, null=True)),
                ('dns_nameserver', models.CharField(blank=True, max_length=255, null=True)),
                ('coe', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('flavor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('master_lb_enabled', models.BooleanField(default=False)),
                ('cluster_distro', models.CharField(blank=True, max_length=255, null=True)),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_driver', models.CharField(blank=True, max_length=255, null=True)),
                ('docker_storage_driver', models.CharField(blank=True, default='devicemapper', max_length=255, null=True)),
                ('network_driver', models.CharField(blank=True, max_length=255, null=True)),
                ('apiserver_port', models.IntegerField(null=True)),
                ('registry_enabled', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=128)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openstack.Project', to_field='project_id')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('keypair', models.CharField(blank=True, max_length=255, null=True)),
                ('stack_id', models.CharField(blank=True, max_length=255, null=True)),
                ('master_flavor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('flavor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('health_status', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=1024, null=True)),
                ('labels', models.CharField(blank=True, max_length=1024, null=True)),
                ('api_address', models.CharField(blank=True, max_length=1024, null=True)),
                ('discovery_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('node_addresses', models.CharField(blank=True, max_length=1024, null=True)),
                ('master_addresses', models.CharField(blank=True, max_length=1024, null=True)),
                ('region', models.CharField(max_length=128)),
                ('master_count', models.IntegerField(default=1)),
                ('node_count', models.IntegerField(default=1)),
                ('create_timeout', models.IntegerField(default=60)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('cluster_template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openstack.ClusterTemplate')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openstack.Project', to_field='project_id')),
            ],
        ),
    ]
