# Generated by Django 2.2.5 on 2019-11-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
        ('openstack', '0030_openstackinstanceflavor_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavorgroup',
            name='reseller',
        ),
        migrations.RemoveField(
            model_name='openstackinstanceflavor',
            name='reseller',
        ),
        migrations.AddField(
            model_name='flavorgroup',
            name='reseller_resources',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flavor_groups', to='reseller.ResellerResources'),
        ),
        migrations.AddField(
            model_name='openstackinstanceflavor',
            name='reseller_resources',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flavors', to='reseller.ResellerResources'),
        ),
    ]
