# Generated by Django 2.2.5 on 2019-11-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0003_resellerresources_plan'),
        ('openstack', '0032_openstackinstanceflavor_used_by_resellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='reseller_resources',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='reseller.ResellerResources'),
        ),
    ]
