# Generated by Django 2.0.2 on 2018-02-20 09:18

from django.db import migrations


LOW_CREDIT_CONTENT = """Hello,

Your account is low on credit.

Based on your current cloud resources usage, your {{ variables.credit }} {{ variables.currency }} credit will
last for {{ variables.credit_hours_left }} hour(s).

To avoid your cloud resources being suspended, please add more credit:

{{ variables.add_credit_url }}


Thank you

"""


SUSPENDED_OUT_OF_CREDIT_CONTENT = """Hello,

Your cloud resources have been suspended because you are out of credit.

To add credit to your account follow this link:

{{ variables.add_credit_url }}


Thank you

"""


PASSWORD_RESET_BODY = """Dear{% if user.first_name and user.last_name %} {{ user.first_name }} {{ user.last_name }},
{% elif user.first_name %} {{ user.first_name }}, {% elif user.last_name %} {{user.last_name}},
{% else %} Customer, {% endif %}
Someone (hopefully you) requested a new password for the user account associated with this email.
No changes have been made to your account yet.

You can reset your password by clicking the link below:
{{ frontend_url }}reset-password/{{ user_id }}/{{ token }}

If you did not request a new password, you can ignore this email or contact support.

Cheers"""


UNPAID_INVOICE_GENERATED = """Hello,

Invoice {{ variables.invoice_id }} with total amount of {{ variables.amount }} {{ variables.currency}} was issued.

To view and pay invoice follow this link:

{{ variables.invoice_url }}

Thank you
"""


def load_email_templates(apps, schema_editor):
    category = apps.get_model('notifications.Category')
    credit_category = category.objects.get(name='credit')
    nt_model = apps.get_model('notifications.NotificationTemplate')
    nt_model.objects.create(name='account.credit.low',
                            category=credit_category,
                            title='Account out of credit in {{ variables.credit_hours_left }} hours',
                            content=LOW_CREDIT_CONTENT)
    nt_model.objects.create(name='account.suspended',
                            category=credit_category,
                            title='Your cloud account has been suspended',
                            content=SUSPENDED_OUT_OF_CREDIT_CONTENT)


def apply_reset_password_email_template(apps, schema_editor):
    category = apps.get_model('notifications.Category')
    account_category = category.objects.get(name='account')
    notification_template_model = apps.get_model('notifications.NotificationTemplate')
    notification_template_model.objects.create(name='account.reset.password',
                                               category=account_category,
                                               title='Password reset',
                                               content=PASSWORD_RESET_BODY
                                               )


def add_billing_category(apps, schema_editor):
    category = apps.get_model('notifications.Category')
    category.objects.create(name='billing', description='Billing related messages')


def add_invoice_templates(apps, schema_editor):
    category = apps.get_model('notifications.Category')
    billing_category = category.objects.get(name='billing')
    nt_model = apps.get_model('notifications.NotificationTemplate')
    nt_model.objects.create(name='billing.invoice.new',
                            category=billing_category,
                            title='Invoice {{ variables.invoice_id }} was issued',
                            content=UNPAID_INVOICE_GENERATED)



class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_categories'),
    ]

    operations = [
        migrations.RunPython(load_email_templates),
        migrations.RunPython(apply_reset_password_email_template),
        migrations.RunPython(add_billing_category),
        migrations.RunPython(add_invoice_templates),
    ]
