# Generated by Django 2.1 on 2018-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ro', 'Română')], default='en', max_length=5),
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='help_text',
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('name', 'dispatcher', 'language')},
        ),
    ]
