# Generated by Django 2.2.1 on 2019-05-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0002_add_foreign_keys'),
        ('tasklog', '0003_allow_longer_resource_name_in_tasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='task',
            name='activity_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='activitylog.Log'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tasklog.Task'),
        ),
    ]
