# Generated by Django 2.1.2 on 2018-11-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('billing', '0006_service_upgrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypanelProductSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('configuration', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.IntegerField(null=True)),
                ('disk_size', models.IntegerField(null=True)),
                ('ip_count', models.IntegerField(default=1)),
                ('traffic', models.IntegerField(null=True)),
                ('machine_type', models.CharField(default='openvz', max_length=10)),
                ('server_group', models.CharField(blank=True, max_length=255, null=True)),
                ('send_welcome_email', models.BooleanField(default=False)),
                ('hypanel_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypanel_server_settings', to='servers.Server')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hypanel_product_settings', to='billing.Product')),
            ],
        ),
    ]
