# Generated by Django 2.2.5 on 2019-09-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_update_country_field_on_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(max_length=1024, null=True)),
                ('stripe_payment_method', models.CharField(max_length=1024, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Client')),
            ],
        ),
    ]
