# Generated by Django 2.1 on 2018-09-25 10:54

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_update_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('managed', models.BooleanField()),
                ('assigned_to_service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_domain', to='billing.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Nameserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('class_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('premium_domains_available', models.BooleanField(default=False)),
                ('edit_options', jsonfield.fields.JSONField(default={})),
                ('default_registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_tlds', to='domains.Registrar')),
                ('register_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.Product')),
                ('registrars', models.ManyToManyField(related_name='tlds', to='domains.Registrar')),
                ('renew_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.Product')),
                ('transfer_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.Product')),
            ],
        ),
        migrations.AddField(
            model_name='registrar',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrars', to='domains.RegistrarConnector'),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.Registrar'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameservers',
            field=models.ManyToManyField(related_name='domains', to='domains.Nameserver'),
        ),
        migrations.AddField(
            model_name='domain',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain', to='billing.Service'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.TLD'),
        ),
    ]
