# Generated by Django 2.1 on 2018-09-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='last_registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.Registrar'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='managed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='nameservers',
            field=models.ManyToManyField(blank=True, related_name='domains', to='domains.Nameserver'),
        ),
    ]
