# Generated by Django 2.1.2 on 2018-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_registrar_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameserver',
            name='host_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
