# Generated by Django 2.1.2 on 2018-10-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_make_nameserver_host_name_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrarconnector',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='registrarprices',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrar_prices', to='domains.RegistrarConnector'),
        ),
        migrations.AddField(
            model_name='registrarprices',
            name='tld_name',
            field=models.CharField(db_index=True, default='.com', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrarconnector',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='registrarprices',
            unique_together={('tld_name', 'connector', 'currency', 'years')},
        ),
        migrations.RemoveField(
            model_name='registrarprices',
            name='registrar',
        ),
        migrations.RemoveField(
            model_name='registrarprices',
            name='tld',
        )
    ]
