# Generated by Django 2.1.2 on 2018-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_domain_registrar_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarconnector',
            name='class_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
