# Generated by Django 2.2.5 on 2019-11-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_change_reseller_relation'),
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerresources',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reseller_resources', to='billing.Service'),
        ),
    ]
