# Generated by Django 2.2.7 on 2019-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0003_resellerresources_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerresources',
            name='enduser_panel_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
