# Generated by Django 2.2.5 on 2019-09-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payuro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayments',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Client'),
        ),
    ]
