# Generated by Django 2.2.5 on 2019-09-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('token_hash', models.CharField(max_length=255)),
                ('ipn_cc_mask', models.CharField(max_length=255)),
                ('ipn_cc_exp_date', models.CharField(max_length=255)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
    ]
