# Generated by Django 2.1.2 on 2018-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_add_staff_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='internal_status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
