# Generated by Django 2.1.5 on 2019-02-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_set_service_as_null_on_tickets_when_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ticket_id_format',
            field=models.CharField(default='%n%n%n%n%n%n', max_length=64),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=1, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
