# Generated by Django 2.1.7 on 2019-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_revenue_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyrevenuereport',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AddField(
            model_name='monthlyrevenuereport',
            name='currency_code',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='monthlyrevenuereport',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=14),
        ),
    ]
