# Generated by Django 2.1.7 on 2019-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrevenuereport',
            name='generating',
            field=models.BooleanField(default=False),
        ),
    ]
